[package]
name = "web3mq_aa_cario"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.2.0"
#snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.5.0" }

[tool.snforge]
# exit_first = true
